project_name: mlops-assignment3
model_name: distilbert-base-uncased
text_column: text
label_column: label
output_dir: ./results
hf_repo_name: your-hf-username/your-model-repo

training:
  version: v1
  epochs: 3
  batch_size: 16
  learning_rate: 0.00003
  weight_decay: 0.01
  test_size: 0.2
  random_state: 42
